version: '2'
services:
    graphql:
        container_name: dashboard
        image: 121364511741.dkr.ecr.us-east-1.amazonaws.com/dashboard:latest
        restart: always
        environment:
            - NODE_ENV=production
        ports:
            - 81:81
        networks:
            - redis

networks:
    redis:
        external: true
